### ISSUE TITLE
No payment options

### ISSUE THREAD

**Issue by StefanPostma** [mollie/PrestaShop1.6#8]
### Expected behavior
expect ideal option as payment option

### Actual behavior
no payment options are shown, mollie does not appear

### Steps to reproduce the behavior
after the order steps during the checkout no payment options shows up.
https://www.kevercentrum.shop/order

![Screenshot 2022-03-15 at 14 02 10](https://user-images.githubusercontent.com/25791863/158383818-ebd70e9b-66f8-4220-803e-00fab2ae3bc5.png)
[snippet.txt](https://github.com/mollie/PrestaShop1.6/files/8253499/snippet.txt)

### Environment
* PrestaShop version: 1.6.1.24 
* Mollie module version: 4.5.0 
* PHP version: 7.1.26

**Comment by loonas** [comment]
Hi @StefanPostma! Hope that you are doing well.

Thank you for reaching out to us regarding this issue. We would be glad to help you resolve it.

As you have mentioned that no payment methods are showing up, could you go to International -> Localization -> Languages in there you will see the tab “Language code” and let us know if the selected language codes are correct?
They should look like this:
![image](https://user-images.githubusercontent.com/30753843/159483348-d9cc86a1-714f-434b-a7da-8801ae875296.png)

Make sure that in there both of the languages codes exist, so if you have your language set as “nl”, it shouldn’t be just “nl” rather “nl-nl”. This applies to other languages as well.

In case this trick does not help, could you share your BO+FTP credentials to support@invertus.eu, so that our developer could look into the issue for you?

Let us know how it goes!

Best regards,
Invertus Support team

**Comment by StefanPostma** [comment]
Hey great that worked out! the Dutcht setting was indeed wrong and set to nl instead of nl-nl
Many thanks

**Comment by loonas** [comment]
I'm glad to hear that it has worked out @StefanPostma!

We are more than happy to help. In case you come across any further issues or questions, let us know!
Have a great day :)

Best regards,
Invertus Support team
